### ISSUE TITLE
[suggestion] FS Driver

### ISSUE THREAD

**Issue by NateDogg1232** [TheCool1James/LiquiDOS#1]
I recommend looking here: http://www.brokenthorn.com/Resources/OSDev11.html
and here: http://www.brokenthorn.com/Resources/OSDev22.html
for refrences for making a FS driver.

**Comment by TheCool1James** [comment]
The second link was god, thanks :)

**Comment by TheCool1James** [comment]
All things are sorted out. We have VFS. Just need a disk driver now :)
